include:
  - project: ultimaker/embedded/prime-jedi
    ref: master
    file: /gitlab_ci_templates/jedi-gitlab-ci-template.yml

complexity:
  extends:
    - .jobs_common
    - .build_test_common
  stage: test
  script:
    - ./ci/complexity_analysis.sh

dead_code:
  extends:
    - .jobs_common
    - .build_test_common
  stage: test
  script:
    - ./ci/dead_code_analysis.sh

style:
  extends:
    - .jobs_common
    - .build_test_common
  stage: test
  script:
    - git fetch origin master:master
    - ./ci/style_analysis.sh

mypy:
  extends:
    - .jobs_common
    - .build_test_common
  stage: test
  script:
    - git fetch origin master:master
    - ./ci/mypy.sh

pytest:
    extends:
        - .jobs_common
        - .build_test_common
    stage: test
    script:
        - ./ci/pytest.sh
